CREATE DATABASE Senatur_Manha

USE Senatur_Manha

CREATE TABLE Pacotes (
	IdPacote   INT PRIMARY KEY IDENTITY,
	NomePacote VARCHAR (255) NOT NULL,
	Descricao  VARCHAR (1000) NOT NULL,
	DataIda	   DATE NOT NULL,
	DataVolta  DATE NOT NULL,
	Valor	   DECIMAL NOT NULL,
	Ativo	   BIT NOT NULL,
	NomeCidade VARCHAR (255) NOT NULL

);
GO

CREATE TABLE TiposUsuario (
	 IdTipoUsuario INT PRIMARY KEY IDENTITY,
	 Titulo		   VARCHAR (255) 
);
GO

CREATE TABLE Usuarios (
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR (255) NOT NULL,
	Senha VARCHAR (255) NOT NULL, 
	IdTipoUsuario INT FOREIGN KEY REFERENCES TiposUsuario (IdTipoUsuario)
);
GO